/* الاستعمار أحقاد وأطماع — COLONIALISM — app.js */
/* Based on "Al-Isti'mar Ahqad wa Atma'" by Sheikh Mohammed al-Ghazali (1917-1996) */

const T = {
  ar: {
    appTitle: 'الاستعمار أحقاد وأطماع',
    splashSub: 'كشف حقيقة الاستعمار وأطماعه',
    splashHint: 'اضغط للتخطي',
    sacredRef: 'سورة البقرة ٢: ١٢٠',
    tabHome: 'الرئيسية', tabCards: 'البطاقات', tabResistance: 'المقاومة',
    tabHabits: 'العادات', tabQuiz: 'اختبار', tabAbout: 'الكتاب',
    cardsTitle: 'بطاقات الاستعمار',
    cardsDesc: '٢٠ بطاقة تكشف أحقاد الاستعمار وأطماعه عبر التاريخ',
    resistanceTitle: 'طريق المقاومة',
    resistanceDesc: 'كيف واجه المسلمون الاستعمار وكيف نواجه الاستعمار الجديد',
    habitsTitle: 'عاداتي اليومية',
    habitsDesc: 'عادات لبناء الوعي والاستقلال الفكري',
    quizTitle: 'اختبر وعيك',
    quizDesc: 'هل تفهم حقيقة الاستعمار وأشكاله الجديدة؟',
    helpTitle: '❓ مساعدة',
    duaPanelTitle: '🤲 أدعية للتحرر والاستقلال',
    resetBtn: 'إعادة تعيين اليوم',
    submitQuiz: 'اعرف النتيجة',
    dailyLabel: '✨ فكرة اليوم',
    quizAgain: 'أعد الاختبار',
    yes: 'نعم', no: 'لا', sometimes: 'أحياناً',
    share: 'مشاركة',
    searchPlaceholder: 'ابحث في البطاقات...',
    streakMsg: 'يوم متتالي!',
    allDone: 'أحسنت! أكملت جميع العادات!',
    splashFeatures: ['٢٠ بطاقة عن الاستعمار','طريق المقاومة — حلول إسلامية','عادات يومية للوعي','اختبار + أدعية'],
  },
  en: {
    appTitle: 'Colonialism: Grudges & Greed',
    splashSub: 'Exposing the reality of colonialism',
    splashHint: 'tap to skip',
    sacredRef: 'Surah Al-Baqarah 2:120',
    tabHome: 'Home', tabCards: 'Cards', tabResistance: 'Resistance',
    tabHabits: 'Habits', tabQuiz: 'Quiz', tabAbout: 'Book',
    cardsTitle: 'Colonialism Cards',
    cardsDesc: '20 cards exposing colonial grudges and greed throughout history',
    resistanceTitle: 'The Path of Resistance',
    resistanceDesc: 'How Muslims faced colonialism and how to face neo-colonialism',
    habitsTitle: 'My Daily Habits',
    habitsDesc: 'Habits for building awareness and intellectual independence',
    quizTitle: 'Test Your Awareness',
    quizDesc: 'Do you understand colonialism and its new forms?',
    helpTitle: '❓ Help',
    duaPanelTitle: '🤲 Duas for Liberation & Independence',
    resetBtn: 'Reset Today',
    submitQuiz: 'See Results',
    dailyLabel: '✨ Today\'s Insight',
    quizAgain: 'Retake Quiz',
    yes: 'Yes', no: 'No', sometimes: 'Sometimes',
    share: 'Share',
    searchPlaceholder: 'Search cards...',
    streakMsg: 'day streak!',
    allDone: 'Well done! All habits completed!',
    splashFeatures: ['20 cards on colonialism','The path of resistance — Islamic solutions','Daily awareness habits','Quiz + duas'],
  },
  fr: {
    appTitle: 'Le Colonialisme : Rancunes et Avidité',
    splashSub: 'Dévoiler la réalité du colonialisme',
    splashHint: 'appuyez pour passer',
    sacredRef: 'Sourate Al-Baqarah 2:120',
    tabHome: 'Accueil', tabCards: 'Cartes', tabResistance: 'Résistance',
    tabHabits: 'Habitudes', tabQuiz: 'Quiz', tabAbout: 'Livre',
    cardsTitle: 'Cartes du Colonialisme',
    cardsDesc: '20 cartes exposant les rancunes et l\'avidité coloniales à travers l\'histoire',
    resistanceTitle: 'Le Chemin de la Résistance',
    resistanceDesc: 'Comment les musulmans ont affronté le colonialisme et comment affronter le néo-colonialisme',
    habitsTitle: 'Mes Habitudes Quotidiennes',
    habitsDesc: 'Habitudes pour développer la conscience et l\'indépendance intellectuelle',
    quizTitle: 'Testez Votre Conscience',
    quizDesc: 'Comprenez-vous le colonialisme et ses nouvelles formes ?',
    helpTitle: '❓ Aide',
    duaPanelTitle: '🤲 Duas pour la Libération',
    resetBtn: 'Réinitialiser',
    submitQuiz: 'Voir les Résultats',
    dailyLabel: '✨ Pensée du Jour',
    quizAgain: 'Refaire le Quiz',
    yes: 'Oui', no: 'Non', sometimes: 'Parfois',
    share: 'Partager',
    searchPlaceholder: 'Rechercher les cartes...',
    streakMsg: 'jours consécutifs !',
    allDone: 'Bravo ! Toutes les habitudes accomplies !',
    splashFeatures: ['20 cartes sur le colonialisme','Le chemin de la résistance','Habitudes quotidiennes','Quiz + duas'],
  }
};

const CARDS = [
  { id:1, emoji:'⚔️', ar:{title:'حقيقة الاستعمار',desc:'الاستعمار ليس مجرد احتلال عسكري بل مشروع شامل لنهب الثروات وتدمير الهوية وإخضاع الشعوب.',quran:'وَدُّوا لَوْ تَكْفُرُونَ كَمَا كَفَرُوا فَتَكُونُونَ سَوَاءً',quranRef:'النساء ٤: ٨٩',lesson:'فهم حقيقة الاستعمار أول خطوة لمقاومته'}, en:{title:'The Reality of Colonialism',desc:'Colonialism is not just military occupation but a comprehensive project to plunder wealth, destroy identity, and subjugate peoples.',quran:'"They wish you would disbelieve as they disbelieved so you would be alike"',quranRef:'An-Nisa 4:89',lesson:'Understanding colonialism\'s reality is the first step to resisting it'}, fr:{title:'La Réalité du Colonialisme',desc:'Le colonialisme n\'est pas qu\'une occupation militaire mais un projet global de pillage des richesses, destruction de l\'identité et assujettissement des peuples.',quran:'« Ils souhaitent que vous mécroiriez comme ils ont mécru, pour que vous soyez pareils »',quranRef:'An-Nisa 4:89',lesson:'Comprendre la réalité du colonialisme est le premier pas pour y résister'} },
  { id:2, emoji:'🏴', ar:{title:'الحملات الصليبية',desc:'الحروب الصليبية كانت بداية المواجهة بين الغرب والعالم الإسلامي. أطماع دينية واقتصادية غُلّفت بالدين.',quran:'وَلَا يَزَالُونَ يُقَاتِلُونَكُمْ حَتَّىٰ يَرُدُّوكُمْ عَن دِينِكُمْ إِنِ اسْتَطَاعُوا',quranRef:'البقرة ٢: ٢١٧',lesson:'التاريخ يعيد نفسه — الأطماع لم تتغير'}, en:{title:'The Crusades',desc:'The Crusades were the beginning of the confrontation between the West and the Islamic world. Religious and economic greed wrapped in religion.',quran:'"They will continue to fight you until they turn you back from your religion, if they can"',quranRef:'Al-Baqarah 2:217',lesson:'History repeats itself — the greed has not changed'}, fr:{title:'Les Croisades',desc:'Les Croisades furent le début de la confrontation entre l\'Occident et le monde islamique. Avidité religieuse et économique enveloppée de religion.',quran:'« Ils ne cesseront de vous combattre jusqu\'à ce qu\'ils vous détournent de votre religion, s\'ils le peuvent »',quranRef:'Al-Baqarah 2:217',lesson:'L\'histoire se répète — l\'avidité n\'a pas changé'} },
  { id:3, emoji:'💎', ar:{title:'نهب الثروات',desc:'المستعمر لم يأتِ ليحضّر بل لينهب. ثروات إفريقيا وآسيا نُقلت إلى أوروبا لتبني حضارتها على حساب الشعوب.',quran:'وَلَا تَحْسَبَنَّ اللَّهَ غَافِلًا عَمَّا يَعْمَلُ الظَّالِمُونَ',quranRef:'إبراهيم ١٤: ٤٢',lesson:'النهب المنظم هو جوهر الاستعمار'}, en:{title:'Plundering Wealth',desc:'The colonizer did not come to civilize but to plunder. Africa\'s and Asia\'s wealth was transferred to Europe to build its civilization at peoples\' expense.',quran:'"And never think that God is unaware of what the wrongdoers do"',quranRef:'Ibrahim 14:42',lesson:'Systematic plunder is the essence of colonialism'}, fr:{title:'Le Pillage des Richesses',desc:'Le colonisateur n\'est pas venu pour civiliser mais pour piller. Les richesses d\'Afrique et d\'Asie ont été transférées en Europe pour bâtir sa civilisation aux dépens des peuples.',quran:'« Ne pense jamais que Dieu est inattentif à ce que font les injustes »',quranRef:'Ibrahim 14:42',lesson:'Le pillage systématique est l\'essence du colonialisme'} },
  { id:4, emoji:'📚', ar:{title:'الغزو الثقافي',desc:'أخطر أنواع الاستعمار هو الغزو الثقافي. تدمير اللغة والهوية والقيم أشد فتكاً من الاحتلال العسكري.',quran:'وَلَن تَرْضَىٰ عَنكَ الْيَهُودُ وَلَا النَّصَارَىٰ حَتَّىٰ تَتَّبِعَ مِلَّتَهُمْ',quranRef:'البقرة ٢: ١٢٠',lesson:'حماية الهوية الثقافية مقاومة حقيقية'}, en:{title:'Cultural Invasion',desc:'The most dangerous colonialism is cultural invasion. Destroying language, identity, and values is deadlier than military occupation.',quran:'"Never will the Jews or Christians be satisfied with you until you follow their way"',quranRef:'Al-Baqarah 2:120',lesson:'Protecting cultural identity is true resistance'}, fr:{title:'L\'Invasion Culturelle',desc:'Le colonialisme le plus dangereux est l\'invasion culturelle. Détruire la langue, l\'identité et les valeurs est plus meurtrier que l\'occupation militaire.',quran:'« Ni les juifs ni les chrétiens ne seront satisfaits de toi tant que tu ne suivras pas leur voie »',quranRef:'Al-Baqarah 2:120',lesson:'Protéger l\'identité culturelle est une vraie résistance'} },
  { id:5, emoji:'🕌', ar:{title:'محاربة الإسلام',desc:'الاستعمار استهدف الإسلام بشكل خاص لأنه القوة الوحيدة التي أعاقت مشاريعه.',quran:'يُرِيدُونَ أَن يُطْفِئُوا نُورَ اللَّهِ بِأَفْوَاهِهِمْ وَيَأْبَى اللَّهُ إِلَّا أَن يُتِمَّ نُورَهُ',quranRef:'التوبة ٩: ٣٢',lesson:'محاربة الإسلام هدف استعماري ثابت'}, en:{title:'War on Islam',desc:'Colonialism specifically targeted Islam because it was the only force that blocked colonial projects.',quran:'"They want to extinguish God\'s light with their mouths, but God refuses except to perfect His light"',quranRef:'At-Tawbah 9:32',lesson:'War on Islam is a constant colonial goal'}, fr:{title:'La Guerre Contre l\'Islam',desc:'Le colonialisme a spécifiquement ciblé l\'Islam car c\'était la seule force qui bloquait les projets coloniaux.',quran:'« Ils veulent éteindre la lumière de Dieu avec leurs bouches, mais Dieu refuse sauf à parfaire Sa lumière »',quranRef:'At-Tawbah 9:32',lesson:'La guerre contre l\'Islam est un objectif colonial constant'} },
  { id:6, emoji:'🎓', ar:{title:'التبشير والتعليم',desc:'استخدم المستعمر التبشير والتعليم الغربي كأدوات لتغيير عقول الشعوب وقطعها عن جذورها.',quran:'وَإِذَا تُتْلَىٰ عَلَيْهِمْ آيَاتُنَا بَيِّنَاتٍ قَالُوا مَا هَٰذَا إِلَّا رَجُلٌ يُرِيدُ أَن يَصُدَّكُمْ عَمَّا كَانَ يَعْبُدُ آبَاؤُكُمْ',quranRef:'سبأ ٣٤: ٤٣',lesson:'التعليم سلاح ذو حدين — يمكن أن يحرر أو يستعبد'}, en:{title:'Missionary Work and Education',desc:'The colonizer used missionary work and Western education as tools to change peoples\' minds and cut them from their roots.',quran:'"When Our clear verses are recited to them, they say: This is only a man who wants to turn you away from what your fathers worshipped"',quranRef:'Saba 34:43',lesson:'Education is a double-edged sword — it can liberate or enslave'}, fr:{title:'Le Prosélytisme et l\'Éducation',desc:'Le colonisateur a utilisé le prosélytisme et l\'éducation occidentale comme outils pour changer les esprits des peuples et les couper de leurs racines.',quran:'« Quand Nos versets clairs leur sont récités, ils disent : ce n\'est qu\'un homme qui veut vous détourner de ce que vos pères adoraient »',quranRef:'Saba 34:43',lesson:'L\'éducation est une arme à double tranchant — elle peut libérer ou asservir'} },
  { id:7, emoji:'🗺️', ar:{title:'تقسيم العالم الإسلامي',desc:'قسّم الاستعمار الأمة الإسلامية إلى دول صغيرة متنازعة. سايكس بيكو نموذج صارخ.',quran:'وَاعْتَصِمُوا بِحَبْلِ اللَّهِ جَمِيعًا وَلَا تَفَرَّقُوا',quranRef:'آل عمران ٣: ١٠٣',lesson:'التقسيم كان مخططاً لإضعاف الأمة'}, en:{title:'Dividing the Islamic World',desc:'Colonialism divided the Islamic nation into small quarreling states. Sykes-Picot is a glaring example.',quran:'"And hold firmly to the rope of God all together and do not become divided"',quranRef:'Aal Imran 3:103',lesson:'Division was a plan to weaken the nation'}, fr:{title:'La Division du Monde Islamique',desc:'Le colonialisme a divisé la nation islamique en petits États querelleurs. Sykes-Picot est un exemple flagrant.',quran:'« Et cramponnez-vous tous ensemble au câble de Dieu et ne vous divisez pas »',quranRef:'Aal Imran 3:103',lesson:'La division était un plan pour affaiblir la nation'} },
  { id:8, emoji:'🇩🇿', ar:{title:'الجزائر نموذج المقاومة',desc:'قاومت الجزائر الاستعمار الفرنسي ١٣٢ سنة وقدمت مليون ونصف شهيد. نموذج فريد في الصمود.',quran:'وَلَا تَحْسَبَنَّ الَّذِينَ قُتِلُوا فِي سَبِيلِ اللَّهِ أَمْوَاتًا بَلْ أَحْيَاءٌ عِندَ رَبِّهِمْ يُرْزَقُونَ',quranRef:'آل عمران ٣: ١٦٩',lesson:'المقاومة تحتاج إيماناً وصبراً طويلاً'}, en:{title:'Algeria: A Model of Resistance',desc:'Algeria resisted French colonialism for 132 years and sacrificed 1.5 million martyrs. A unique model of resilience.',quran:'"And do not think of those who have been killed in the cause of God as dead. Rather, they are alive with their Lord"',quranRef:'Aal Imran 3:169',lesson:'Resistance requires faith and long patience'}, fr:{title:'L\'Algérie : Modèle de Résistance',desc:'L\'Algérie a résisté au colonialisme français pendant 132 ans et a sacrifié 1,5 million de martyrs. Un modèle unique de résilience.',quran:'« Et ne pense pas que ceux qui ont été tués dans le chemin de Dieu sont morts. Au contraire, ils sont vivants auprès de leur Seigneur »',quranRef:'Aal Imran 3:169',lesson:'La résistance requiert foi et longue patience'} },
  { id:9, emoji:'🇵🇸', ar:{title:'فلسطين والاستعمار الاستيطاني',desc:'فلسطين نموذج حي للاستعمار الاستيطاني. زراعة كيان غريب في قلب الأمة الإسلامية.',quran:'أُذِنَ لِلَّذِينَ يُقَاتَلُونَ بِأَنَّهُمْ ظُلِمُوا وَإِنَّ اللَّهَ عَلَىٰ نَصْرِهِمْ لَقَدِيرٌ',quranRef:'الحج ٢٢: ٣٩',lesson:'فلسطين قضية كل مسلم وكل حر'}, en:{title:'Palestine and Settler Colonialism',desc:'Palestine is a living example of settler colonialism. Planting a foreign entity in the heart of the Islamic nation.',quran:'"Permission to fight has been given to those who are being fought because they were wronged. And indeed, God is competent to give them victory"',quranRef:'Al-Hajj 22:39',lesson:'Palestine is the cause of every Muslim and every free person'}, fr:{title:'La Palestine et le Colonialisme de Peuplement',desc:'La Palestine est un exemple vivant de colonialisme de peuplement. Implanter une entité étrangère au cœur de la nation islamique.',quran:'« Permission de combattre est donnée à ceux qui sont combattus car ils ont été lésés. Et certes, Dieu est capable de leur donner la victoire »',quranRef:'Al-Hajj 22:39',lesson:'La Palestine est la cause de chaque musulman et de chaque personne libre'} },
  { id:10, emoji:'💀', ar:{title:'الإبادة الجماعية',desc:'ارتكب الاستعمار مجازر مروعة: إبادة الهنود الحمر، مجازر الجزائر، المجاعات المصطنعة في الهند.',quran:'مِنْ أَجْلِ ذَٰلِكَ كَتَبْنَا عَلَىٰ بَنِي إِسْرَائِيلَ أَنَّهُ مَن قَتَلَ نَفْسًا بِغَيْرِ نَفْسٍ أَوْ فَسَادٍ فِي الْأَرْضِ فَكَأَنَّمَا قَتَلَ النَّاسَ جَمِيعًا',quranRef:'المائدة ٥: ٣٢',lesson:'جرائم الاستعمار لا تسقط بالتقادم'}, en:{title:'Genocide',desc:'Colonialism committed horrific massacres: the genocide of Native Americans, the massacres of Algeria, the manufactured famines in India.',quran:'"Whoever kills a soul unless for a soul or for corruption done in the land — it is as if he had killed all mankind"',quranRef:'Al-Ma\'idah 5:32',lesson:'Colonial crimes do not expire with time'}, fr:{title:'Le Génocide',desc:'Le colonialisme a commis des massacres horribles : le génocide des Amérindiens, les massacres d\'Algérie, les famines manufacturées en Inde.',quran:'« Quiconque tue une âme sans que ce soit en raison d\'un meurtre ou de corruption sur terre, c\'est comme s\'il avait tué l\'humanité entière »',quranRef:'Al-Ma\'idah 5:32',lesson:'Les crimes coloniaux ne se prescrivent pas avec le temps'} },
  { id:11, emoji:'⛓️', ar:{title:'العبودية والاتجار بالبشر',desc:'الاستعمار الغربي مارس تجارة العبيد لقرون. ملايين الأفارقة نُقلوا قسراً عبر المحيط.',quran:'وَمَا كَانَ لِمُؤْمِنٍ وَلَا مُؤْمِنَةٍ إِذَا قَضَى اللَّهُ وَرَسُولُهُ أَمْرًا أَن يَكُونَ لَهُمُ الْخِيَرَةُ',quranRef:'الأحزاب ٣٣: ٣٦',lesson:'الإسلام حارب العبودية بينما الاستعمار أسسها'}, en:{title:'Slavery and Human Trafficking',desc:'Western colonialism practiced the slave trade for centuries. Millions of Africans were forcibly transported across the ocean.',quran:'"It is not for a believing man or woman, when God and His Messenger have decided a matter, to have any choice in their affair"',quranRef:'Al-Ahzab 33:36',lesson:'Islam fought slavery while colonialism institutionalized it'}, fr:{title:'L\'Esclavage et la Traite des Êtres Humains',desc:'Le colonialisme occidental a pratiqué la traite des esclaves pendant des siècles. Des millions d\'Africains ont été transportés de force à travers l\'océan.',quran:'« Il n\'appartient pas à un croyant ou une croyante, quand Dieu et Son Messager ont décidé d\'une chose, d\'avoir le choix dans leur affaire »',quranRef:'Al-Ahzab 33:36',lesson:'L\'Islam a combattu l\'esclavage alors que le colonialisme l\'a institutionnalisé'} },
  { id:12, emoji:'🏭', ar:{title:'الاستعمار الاقتصادي',desc:'بعد الاستقلال السياسي بقي الاستعمار الاقتصادي. الديون والشروط الدولية أدوات سيطرة جديدة.',quran:'يَا أَيُّهَا الَّذِينَ آمَنُوا لَا تَأْكُلُوا الرِّبَا أَضْعَافًا مُّضَاعَفَةً',quranRef:'آل عمران ٣: ١٣٠',lesson:'الاستقلال الاقتصادي شرط للاستقلال الحقيقي'}, en:{title:'Economic Colonialism',desc:'After political independence, economic colonialism remained. Debts and international conditions are new tools of control.',quran:'"O you who believe, do not consume interest multiplied many times over"',quranRef:'Aal Imran 3:130',lesson:'Economic independence is a condition for true independence'}, fr:{title:'Le Colonialisme Économique',desc:'Après l\'indépendance politique, le colonialisme économique est resté. Les dettes et les conditions internationales sont de nouveaux outils de contrôle.',quran:'« Ô vous qui croyez, ne pratiquez pas l\'intérêt multiplié plusieurs fois »',quranRef:'Aal Imran 3:130',lesson:'L\'indépendance économique est une condition pour la vraie indépendance'} },
  { id:13, emoji:'📺', ar:{title:'الاستعمار الإعلامي',desc:'وسائل الإعلام الغربية تصنع صورة مشوهة عن الإسلام والمسلمين. حرب نفسية منظمة.',quran:'وَلَا تَلْبِسُوا الْحَقَّ بِالْبَاطِلِ وَتَكْتُمُوا الْحَقَّ وَأَنتُمْ تَعْلَمُونَ',quranRef:'البقرة ٢: ٤٢',lesson:'الوعي الإعلامي سلاح ضد التضليل'}, en:{title:'Media Colonialism',desc:'Western media creates a distorted image of Islam and Muslims. An organized psychological warfare.',quran:'"And do not mix truth with falsehood or conceal the truth while you know it"',quranRef:'Al-Baqarah 2:42',lesson:'Media awareness is a weapon against deception'}, fr:{title:'Le Colonialisme Médiatique',desc:'Les médias occidentaux créent une image déformée de l\'Islam et des musulmans. Une guerre psychologique organisée.',quran:'« Et ne mêlez pas le vrai avec le faux et ne cachez pas la vérité alors que vous la savez »',quranRef:'Al-Baqarah 2:42',lesson:'La conscience médiatique est une arme contre la désinformation'} },
  { id:14, emoji:'🧪', ar:{title:'الاستشراق',desc:'الاستشراق كان الذراع الفكري للاستعمار. دراسة الشرق لفهمه ثم السيطرة عليه.',quran:'قَدْ بَدَتِ الْبَغْضَاءُ مِنْ أَفْوَاهِهِمْ وَمَا تُخْفِي صُدُورُهُمْ أَكْبَرُ',quranRef:'آل عمران ٣: ١١٨',lesson:'ليس كل دراسة أكاديمية بريئة'}, en:{title:'Orientalism',desc:'Orientalism was the intellectual arm of colonialism. Studying the East to understand it and then control it.',quran:'"Hatred has already appeared from their mouths, and what their hearts conceal is greater"',quranRef:'Aal Imran 3:118',lesson:'Not every academic study is innocent'}, fr:{title:'L\'Orientalisme',desc:'L\'orientalisme était le bras intellectuel du colonialisme. Étudier l\'Orient pour le comprendre puis le contrôler.',quran:'« La haine a déjà paru de leurs bouches, et ce que cachent leurs poitrines est plus grand »',quranRef:'Aal Imran 3:118',lesson:'Toute étude académique n\'est pas innocente'} },
  { id:15, emoji:'🌍', ar:{title:'الاستعمار الجديد',desc:'الاستعمار الجديد يعمل بأدوات ناعمة: ديون، منظمات دولية، ثقافة استهلاكية، هيمنة تكنولوجية.',quran:'وَلَا تَهِنُوا وَلَا تَحْزَنُوا وَأَنتُمُ الْأَعْلَوْنَ إِن كُنتُم مُّؤْمِنِينَ',quranRef:'آل عمران ٣: ١٣٩',lesson:'الاستعمار تغير شكله لكن لم يتغير جوهره'}, en:{title:'Neo-Colonialism',desc:'Neo-colonialism works with soft tools: debts, international organizations, consumer culture, technological hegemony.',quran:'"Do not lose heart and do not grieve, for you are the superior ones if you are believers"',quranRef:'Aal Imran 3:139',lesson:'Colonialism changed its form but not its essence'}, fr:{title:'Le Néo-Colonialisme',desc:'Le néo-colonialisme fonctionne avec des outils doux : dettes, organisations internationales, culture de consommation, hégémonie technologique.',quran:'« Ne vous découragez pas et ne vous affligez pas, car vous êtes les supérieurs si vous êtes croyants »',quranRef:'Aal Imran 3:139',lesson:'Le colonialisme a changé de forme mais pas d\'essence'} },
  { id:16, emoji:'🛡️', ar:{title:'المقاومة بالعلم',desc:'أقوى مقاومة هي بناء العلم والمعرفة. أمة جاهلة أمة مستعمَرة حتى لو كانت مستقلة سياسياً.',quran:'اقْرَأْ بِاسْمِ رَبِّكَ الَّذِي خَلَقَ',quranRef:'العلق ٩٦: ١',lesson:'العلم هو أقوى سلاح ضد الاستعمار'}, en:{title:'Resistance Through Knowledge',desc:'The strongest resistance is building knowledge. An ignorant nation is a colonized nation even if politically independent.',quran:'"Read in the name of your Lord who created"',quranRef:'Al-Alaq 96:1',lesson:'Knowledge is the strongest weapon against colonialism'}, fr:{title:'La Résistance par le Savoir',desc:'La plus forte résistance est la construction du savoir. Une nation ignorante est une nation colonisée même si politiquement indépendante.',quran:'« Lis au nom de ton Seigneur qui a créé »',quranRef:'Al-Alaq 96:1',lesson:'Le savoir est l\'arme la plus puissante contre le colonialisme'} },
  { id:17, emoji:'🤝', ar:{title:'وحدة الأمة',desc:'وحدة الأمة الإسلامية هي الردع الأكبر للاستعمار. التفرقة هي أداته المفضلة.',quran:'إِنَّ هَٰذِهِ أُمَّتُكُمْ أُمَّةً وَاحِدَةً وَأَنَا رَبُّكُمْ فَاعْبُدُونِ',quranRef:'الأنبياء ٢١: ٩٢',lesson:'الوحدة قوة والتفرقة ضعف'}, en:{title:'Unity of the Nation',desc:'Unity of the Islamic nation is the greatest deterrent against colonialism. Division is its favorite tool.',quran:'"Indeed this, your nation, is one nation, and I am your Lord, so worship Me"',quranRef:'Al-Anbiya 21:92',lesson:'Unity is strength and division is weakness'}, fr:{title:'L\'Unité de la Nation',desc:'L\'unité de la nation islamique est le plus grand moyen de dissuasion contre le colonialisme. La division est son outil préféré.',quran:'« Certes cette communauté qui est la vôtre est une communauté unique, et Je suis votre Seigneur, adorez-Moi donc »',quranRef:'Al-Anbiya 21:92',lesson:'L\'unité est force et la division est faiblesse'} },
  { id:18, emoji:'💪', ar:{title:'الاعتماد على الذات',desc:'الاعتماد على الذات في الاقتصاد والتكنولوجيا والغذاء هو طريق التحرر الحقيقي.',quran:'وَأَعِدُّوا لَهُم مَّا اسْتَطَعْتُم مِّن قُوَّةٍ',quranRef:'الأنفال ٨: ٦٠',lesson:'القوة الذاتية هي ضمانة الاستقلال'}, en:{title:'Self-Reliance',desc:'Self-reliance in economy, technology, and food is the path to true liberation.',quran:'"And prepare against them whatever you are able of power"',quranRef:'Al-Anfal 8:60',lesson:'Self-power is the guarantee of independence'}, fr:{title:'L\'Autonomie',desc:'L\'autonomie en économie, technologie et alimentation est le chemin vers la vraie libération.',quran:'« Et préparez contre eux tout ce que vous pouvez comme force »',quranRef:'Al-Anfal 8:60',lesson:'La puissance propre est la garantie de l\'indépendance'} },
  { id:19, emoji:'📖', ar:{title:'العودة إلى القرآن',desc:'القرآن هو المرجع الأول للأمة. العودة إليه تمنح الأمة بوصلة واضحة في مواجهة التحديات.',quran:'إِنَّ هَٰذَا الْقُرْآنَ يَهْدِي لِلَّتِي هِيَ أَقْوَمُ',quranRef:'الإسراء ١٧: ٩',lesson:'القرآن منهج حياة لا مجرد كتاب يُتلى'}, en:{title:'Return to the Quran',desc:'The Quran is the first reference for the nation. Returning to it gives the nation a clear compass in facing challenges.',quran:'"Indeed, this Quran guides to that which is most suitable"',quranRef:'Al-Isra 17:9',lesson:'The Quran is a way of life, not just a book to be recited'}, fr:{title:'Le Retour au Coran',desc:'Le Coran est la première référence pour la nation. Y revenir donne à la nation une boussole claire face aux défis.',quran:'« Certes, ce Coran guide vers ce qui est le plus droit »',quranRef:'Al-Isra 17:9',lesson:'Le Coran est un mode de vie, pas juste un livre à réciter'} },
  { id:20, emoji:'🕊️', ar:{title:'نحو أمة حرة',desc:'التحرر الحقيقي يبدأ من تحرر العقل والروح. أمة تعرف ربها وتاريخها لا تُستعمر.',quran:'وَقُلِ الْحَقُّ مِن رَّبِّكُمْ فَمَن شَاءَ فَلْيُؤْمِن وَمَن شَاءَ فَلْيَكْفُرْ',quranRef:'الكهف ١٨: ٢٩',lesson:'الحرية تبدأ من الداخل'}, en:{title:'Toward a Free Nation',desc:'True liberation starts with freeing the mind and spirit. A nation that knows its Lord and its history cannot be colonized.',quran:'"And say: The truth is from your Lord, so whoever wills — let him believe; and whoever wills — let him disbelieve"',quranRef:'Al-Kahf 18:29',lesson:'Freedom starts from within'}, fr:{title:'Vers une Nation Libre',desc:'La vraie libération commence par libérer l\'esprit et l\'âme. Une nation qui connaît son Seigneur et son histoire ne peut être colonisée.',quran:'« Et dis : La vérité vient de votre Seigneur, que celui qui veut croie et que celui qui veut mécroie »',quranRef:'Al-Kahf 18:29',lesson:'La liberté commence de l\'intérieur'} }
];

const RESISTANCE_DATA = [
  { emoji:'📖', ar:{title:'التعليم الأصيل',problem:'التعليم الاستعماري يقطع الأجيال عن هويتها',solution:'بناء نظام تعليمي يجمع بين العلم الحديث والقيم الإسلامية',verse:'هَلْ يَسْتَوِي الَّذِينَ يَعْلَمُونَ وَالَّذِينَ لَا يَعْلَمُونَ',verseRef:'الزمر ٣٩: ٩'}, en:{title:'Authentic Education',problem:'Colonial education cuts generations from their identity',solution:'Build an educational system that combines modern science with Islamic values',verse:'"Are those who know equal to those who do not know?"',verseRef:'Az-Zumar 39:9'}, fr:{title:'L\'Éducation Authentique',problem:'L\'éducation coloniale coupe les générations de leur identité',solution:'Construire un système éducatif qui combine science moderne et valeurs islamiques',verse:'« Sont-ils égaux, ceux qui savent et ceux qui ne savent pas ? »',verseRef:'Az-Zumar 39:9'} },
  { emoji:'💰', ar:{title:'الاستقلال الاقتصادي',problem:'التبعية الاقتصادية تعني استعماراً مستمراً',solution:'تطوير اقتصاد إنتاجي مستقل عن الهيمنة الغربية',verse:'وَأَنفِقُوا فِي سَبِيلِ اللَّهِ وَلَا تُلْقُوا بِأَيْدِيكُمْ إِلَى التَّهْلُكَةِ',verseRef:'البقرة ٢: ١٩٥'}, en:{title:'Economic Independence',problem:'Economic dependence means continuing colonialism',solution:'Develop an independent productive economy free from Western hegemony',verse:'"And spend in the way of God and do not throw yourselves into destruction"',verseRef:'Al-Baqarah 2:195'}, fr:{title:'L\'Indépendance Économique',problem:'La dépendance économique signifie un colonialisme continu',solution:'Développer une économie productive indépendante de l\'hégémonie occidentale',verse:'« Et dépensez dans le chemin de Dieu et ne vous jetez pas dans la destruction »',verseRef:'Al-Baqarah 2:195'} },
  { emoji:'🌐', ar:{title:'الوحدة الإسلامية',problem:'التفرقة بين المسلمين أكبر هدية للمستعمر',solution:'بناء تحالفات إسلامية حقيقية تتجاوز الحدود المصطنعة',verse:'وَاعْتَصِمُوا بِحَبْلِ اللَّهِ جَمِيعًا وَلَا تَفَرَّقُوا',verseRef:'آل عمران ٣: ١٠٣'}, en:{title:'Islamic Unity',problem:'Division among Muslims is the greatest gift to the colonizer',solution:'Build genuine Islamic alliances that transcend artificial borders',verse:'"And hold firmly to the rope of God all together and do not become divided"',verseRef:'Aal Imran 3:103'}, fr:{title:'L\'Unité Islamique',problem:'La division entre musulmans est le plus grand cadeau au colonisateur',solution:'Construire de véritables alliances islamiques qui transcendent les frontières artificielles',verse:'« Et cramponnez-vous tous ensemble au câble de Dieu et ne vous divisez pas »',verseRef:'Aal Imran 3:103'} },
  { emoji:'🛡️', ar:{title:'الوعي الإعلامي',problem:'الإعلام المضلل يشكل الوعي الجمعي',solution:'بناء إعلام بديل صادق يعبر عن هوية الأمة وقضاياها',verse:'يَا أَيُّهَا الَّذِينَ آمَنُوا إِن جَاءَكُمْ فَاسِقٌ بِنَبَإٍ فَتَبَيَّنُوا',verseRef:'الحجرات ٤٩: ٦'}, en:{title:'Media Awareness',problem:'Misleading media shapes collective consciousness',solution:'Build alternative honest media that expresses the nation\'s identity and causes',verse:'"O you who believe, if a wicked person comes to you with news, verify it"',verseRef:'Al-Hujurat 49:6'}, fr:{title:'La Conscience Médiatique',problem:'Les médias trompeurs façonnent la conscience collective',solution:'Construire des médias alternatifs honnêtes qui expriment l\'identité et les causes de la nation',verse:'« Ô vous qui croyez, si un pervers vous apporte une nouvelle, vérifiez-la »',verseRef:'Al-Hujurat 49:6'} },
  { emoji:'🔬', ar:{title:'التقدم العلمي',problem:'التبعية التكنولوجية شكل من أشكال الاستعمار',solution:'الاستثمار في البحث العلمي والتكنولوجيا الذاتية',verse:'وَقُل رَّبِّ زِدْنِي عِلْمًا',verseRef:'طه ٢٠: ١١٤'}, en:{title:'Scientific Progress',problem:'Technological dependence is a form of colonialism',solution:'Invest in scientific research and indigenous technology',verse:'"And say: My Lord, increase me in knowledge"',verseRef:'Taha 20:114'}, fr:{title:'Le Progrès Scientifique',problem:'La dépendance technologique est une forme de colonialisme',solution:'Investir dans la recherche scientifique et la technologie autochtone',verse:'« Et dis : Seigneur, augmente-moi en savoir »',verseRef:'Taha 20:114'} }
];

const HABITS = [
  { emoji:'📖', ar:{label:'قراءة عن تاريخ الاستعمار',source:'الوعي التاريخي'}, en:{label:'Read about colonial history',source:'Historical awareness'}, fr:{label:'Lire sur l\'histoire coloniale',source:'Conscience historique'} },
  { emoji:'🤲', ar:{label:'دعاء لتحرر المستضعفين',source:'أدعية مأثورة'}, en:{label:'Dua for the liberation of the oppressed',source:'Prophetic duas'}, fr:{label:'Dua pour la libération des opprimés',source:'Duas prophétiques'} },
  { emoji:'🔍', ar:{label:'تحقق من مصدر خبر واحد',source:'الوعي الإعلامي'}, en:{label:'Verify one news source',source:'Media awareness'}, fr:{label:'Vérifier une source d\'information',source:'Conscience médiatique'} },
  { emoji:'🛒', ar:{label:'اشترِ منتجاً محلياً',source:'الدعم الاقتصادي'}, en:{label:'Buy a local product',source:'Economic support'}, fr:{label:'Acheter un produit local',source:'Soutien économique'} },
  { emoji:'📚', ar:{label:'تعلم شيئاً جديداً',source:'بناء المعرفة'}, en:{label:'Learn something new',source:'Building knowledge'}, fr:{label:'Apprendre quelque chose de nouveau',source:'Construction du savoir'} },
  { emoji:'🤝', ar:{label:'ساعد شخصاً في مجتمعك',source:'التكافل'}, en:{label:'Help someone in your community',source:'Solidarity'}, fr:{label:'Aider quelqu\'un dans votre communauté',source:'Solidarité'} },
  { emoji:'🕌', ar:{label:'صلاة في وقتها',source:'العبادة'}, en:{label:'Pray on time',source:'Worship'}, fr:{label:'Prier à l\'heure',source:'Adoration'} },
  { emoji:'🌍', ar:{label:'تأمل في نعمة الحرية',source:'الشكر'}, en:{label:'Reflect on the blessing of freedom',source:'Gratitude'}, fr:{label:'Réfléchir au bienfait de la liberté',source:'Gratitude'} }
];

const QUIZ = [
  { ar:'هل تعرف تاريخ استعمار بلدك؟', en:'Do you know the history of colonialism in your country?', fr:'Connaissez-vous l\'histoire du colonialisme dans votre pays ?' },
  { ar:'هل تتأثر بالإعلام الغربي دون تمحيص؟', en:'Are you influenced by Western media without scrutiny?', fr:'Êtes-vous influencé par les médias occidentaux sans discernement ?' },
  { ar:'هل تدعم المنتجات المحلية؟', en:'Do you support local products?', fr:'Soutenez-vous les produits locaux ?' },
  { ar:'هل تفضل الثقافة الغربية على ثقافتك؟', en:'Do you prefer Western culture over your own?', fr:'Préférez-vous la culture occidentale à la vôtre ?' },
  { ar:'هل تعلم أطفالك عن تاريخهم وهويتهم؟', en:'Do you teach your children about their history and identity?', fr:'Enseignez-vous à vos enfants leur histoire et identité ?' },
  { ar:'هل تتابع قضايا الأمة الإسلامية؟', en:'Do you follow the causes of the Islamic nation?', fr:'Suivez-vous les causes de la nation islamique ?' },
  { ar:'هل تعتقد أن الوحدة الإسلامية ممكنة؟', en:'Do you believe Islamic unity is possible?', fr:'Croyez-vous que l\'unité islamique est possible ?' },
  { ar:'هل تسعى لتطوير نفسك علمياً وفكرياً؟', en:'Do you strive to develop yourself intellectually?', fr:'Cherchez-vous à vous développer intellectuellement ?' }
];

const DUAS = [
  { ar:{label:'دعاء التحرر',text:'اللَّهُمَّ حَرِّرْنَا مِنْ كُلِّ قَيْدٍ وَارْزُقْنَا الْحُرِّيَّةَ وَالْكَرَامَةَ',tr:'يا رب حررنا من كل استعباد'}, en:{label:'Dua for Liberation',text:'Allahumma harrirna min kulli qayd warzuqna al-hurriyya wal-karama',tr:'O God, liberate us from every chain and grant us freedom and dignity'}, fr:{label:'Dua pour la Libération',text:'Allahumma harrirna min kulli qayd warzuqna al-hurriyya wal-karama',tr:'Ô Dieu, libère-nous de toute chaîne et accorde-nous liberté et dignité'} },
  { ar:{label:'دعاء النصر',text:'رَبَّنَا أَفْرِغْ عَلَيْنَا صَبْرًا وَثَبِّتْ أَقْدَامَنَا وَانصُرْنَا عَلَى الْقَوْمِ الْكَافِرِينَ',tr:'البقرة ٢: ٢٥٠'}, en:{label:'Dua for Victory',text:'Rabbana afrigh alayna sabran wa thabbit aqdamana wansurna alal qawmil kafireen',tr:'Our Lord, pour patience upon us, plant our feet firm, and give us victory (2:250)'}, fr:{label:'Dua pour la Victoire',text:'Rabbana afrigh alayna sabran wa thabbit aqdamana wansurna alal qawmil kafireen',tr:'Notre Seigneur, déverse sur nous la patience, affermis nos pieds et donne-nous la victoire (2:250)'} },
  { ar:{label:'دعاء الوحدة',text:'اللَّهُمَّ أَلِّفْ بَيْنَ قُلُوبِنَا وَأَصْلِحْ ذَاتَ بَيْنِنَا وَاهْدِنَا سُبُلَ السَّلَامِ',tr:'من دعاء النبي ﷺ'}, en:{label:'Dua for Unity',text:'Allahumma allif bayna quloobina wa aslih dhata baynina wahdina subul as-salam',tr:'O God, bring our hearts together, reconcile between us, and guide us to paths of peace'}, fr:{label:'Dua pour l\'Unité',text:'Allahumma allif bayna quloobina wa aslih dhata baynina wahdina subul as-salam',tr:'Ô Dieu, rassemble nos cœurs, réconcilie entre nous et guide-nous vers les voies de la paix'} },
  { ar:{label:'دعاء العلم',text:'اللَّهُمَّ انْفَعْنِي بِمَا عَلَّمْتَنِي وَعَلِّمْنِي مَا يَنْفَعُنِي وَزِدْنِي عِلْمًا',tr:'حديث شريف'}, en:{label:'Dua for Knowledge',text:'Allahumma infa\'ni bima allamtani wa allimni ma yanfa\'uni wa zidni ilma',tr:'O God, benefit me by what You have taught me, teach me what will benefit me, and increase me in knowledge'}, fr:{label:'Dua pour le Savoir',text:'Allahumma infa\'ni bima allamtani wa allimni ma yanfa\'uni wa zidni ilma',tr:'Ô Dieu, fais-moi profiter de ce que Tu m\'as enseigné, enseigne-moi ce qui me sera utile et augmente-moi en savoir'} },
  { ar:{label:'دعاء حسن الخاتمة',text:'رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ',tr:'البقرة ٢: ٢٠١'}, en:{label:'Dua for Good End',text:'Rabbana atina fid-dunya hasanatan wa fil akhirati hasanatan wa qina adhab an-nar',tr:'Our Lord, give us good in this world and in the Hereafter and protect us from the Fire (2:201)'}, fr:{label:'Dua pour une Bonne Fin',text:'Rabbana atina fid-dunya hasanatan wa fil akhirati hasanatan wa qina adhab an-nar',tr:'Notre Seigneur, donne-nous le bien ici-bas et dans l\'au-delà et protège-nous du Feu (2:201)'} }
];

let lang = localStorage.getItem('istimar-lang') || 'ar';
const themes = ['earth', 'night', 'resistance'];
const themeIcons = ['🏴', '🌙', '🛡️'];
const themeNames = { earth:'Earth — أرضي', night:'Night — ليلي', resistance:'Resistance — مقاومة' };
let theme = localStorage.getItem('istimar-theme') || 'earth';
let currentCardIdx = -1;

document.addEventListener('DOMContentLoaded', () => {
  setTheme(theme); setLang(lang); initTabs(); initSplash(); initScrollTop(); initSwipeGestures(); initParticles();
  renderHome(); renderCards(); renderResistance(); renderHabits(); renderQuiz(); renderAbout(); renderHelp(); renderDuas(); initScrollReveal(); initKeyboardNav();
});

function initSplash() {
  let count = 5; const el = document.getElementById('splashCount');
  const featuresEl = document.getElementById('splashFeatures');
  if (featuresEl) featuresEl.innerHTML = T[lang].splashFeatures.map((f, i) => `<div class="splash-feature" style="animation-delay:${0.3 + i * 0.3}s">${f}</div>`).join('');
  const interval = setInterval(() => { count--; if (el) el.textContent = count; if (count <= 0) { dismissSplash(); clearInterval(interval); } }, 1000);
}
function dismissSplash() { const s = document.getElementById('splash'); if (s) { s.classList.add('hidden'); setTimeout(() => s.style.display = 'none', 500); } playSound('click'); }

function setLang(l) {
  lang = l; localStorage.setItem('istimar-lang', l);
  const isRTL = l === 'ar'; document.documentElement.lang = l; document.documentElement.dir = isRTL ? 'rtl' : 'ltr'; document.body.dir = isRTL ? 'rtl' : 'ltr';
  document.querySelectorAll('.lang-opt').forEach(b => b.classList.toggle('active', b.dataset.lang === l));
  const t = T[l]; const set = (id, val) => { const el = document.getElementById(id); if (el) el.textContent = val; };
  set('appTitle', t.appTitle); set('splashSub', t.splashSub); set('splashHint', t.splashHint);
  set('tabHome', t.tabHome); set('tabCards', t.tabCards); set('tabResistance', t.tabResistance);
  set('tabHabits', t.tabHabits); set('tabQuiz', t.tabQuiz); set('tabAbout', t.tabAbout);
  set('cardsTitle', t.cardsTitle); set('cardsDesc', t.cardsDesc);
  set('resistanceTitle', t.resistanceTitle); set('resistanceDesc', t.resistanceDesc);
  set('habitsTitle', t.habitsTitle); set('habitsDesc', t.habitsDesc);
  set('quizTitle', t.quizTitle); set('quizDesc', t.quizDesc);
  set('helpTitle', t.helpTitle); set('duaPanelTitle', t.duaPanelTitle); set('habitsReset', t.resetBtn);
  renderHome(); renderCards(); renderResistance(); renderHabits(); renderQuiz(); renderAbout(); renderHelp(); renderDuas();
  const featuresEl = document.getElementById('splashFeatures');
  if (featuresEl) featuresEl.innerHTML = T[l].splashFeatures.map((f, i) => `<div class="splash-feature" style="animation-delay:${0.3 + i * 0.3}s">${f}</div>`).join('');
}

function setTheme(t) { theme = t; document.documentElement.dataset.theme = t; localStorage.setItem('istimar-theme', t); const idx = themes.indexOf(t); const el = document.getElementById('themeIcon'); if (el) el.textContent = themeIcons[idx]; }
function cycleTheme() { const idx = (themes.indexOf(theme) + 1) % themes.length; setTheme(themes[idx]); showToast(themeNames[themes[idx]]); playSound('theme'); }

function initTabs() { document.querySelectorAll('.tab').forEach(tab => { tab.addEventListener('click', () => { document.querySelectorAll('.tab').forEach(t => t.classList.remove('active')); document.querySelectorAll('.panel').forEach(p => p.classList.remove('active')); tab.classList.add('active'); const panel = document.getElementById('panel-' + tab.dataset.tab); if (panel) panel.classList.add('active'); window.scrollTo({top:0, behavior:'smooth'}); playSound('click'); }); }); }

function renderHome() {
  const t = T[lang]; const dayIdx = new Date().getDate() % CARDS.length; const c = CARDS[dayIdx]; const cd = c[lang];
  document.getElementById('dailyCard').innerHTML = `<div class="daily-label">${t.dailyLabel}</div><div class="daily-title">${cd.title}</div><div class="daily-body">${cd.desc}</div><div class="daily-action" onclick="document.querySelector('[data-tab=cards]').click()">${t.tabCards} &#8594;</div>`;
  const sections = [{icon:'🏴',tab:'cards',title:t.tabCards,desc:lang==='ar'?'٢٠ بطاقة':lang==='fr'?'20 cartes':'20 cards'},{icon:'🛡️',tab:'resistance',title:t.tabResistance,desc:lang==='ar'?'طريق المقاومة':lang==='fr'?'Chemin de résistance':'Path of resistance'},{icon:'📋',tab:'habits',title:t.tabHabits,desc:lang==='ar'?'تتبع يومي':lang==='fr'?'Suivi quotidien':'Daily tracking'},{icon:'🤔',tab:'quiz',title:t.tabQuiz,desc:lang==='ar'?'اختبر وعيك':lang==='fr'?'Testez-vous':'Test yourself'},{icon:'📖',tab:'about',title:t.tabAbout,desc:lang==='ar'?'عن الكتاب':lang==='fr'?'Le livre':'The book'}];
  document.getElementById('homeGrid').innerHTML = sections.map(s => `<div class="home-card" onclick="document.querySelector('[data-tab=${s.tab}]').click()"><span class="hc-icon">${s.icon}</span><div class="hc-title">${s.title}</div><div class="hc-desc">${s.desc}</div></div>`).join('');
}

function renderCards() {
  const t = T[lang];
  const searchBar = `<div class="search-bar"><input type="text" id="cardsSearch" class="search-input" placeholder="${t.searchPlaceholder}" oninput="filterCards(this.value)"><span class="search-icon">🔍</span></div>`;
  const cards = CARDS.map((c, i) => { const d = c[lang]; return `<div class="principle-card scroll-reveal" id="card-${c.id}" data-search="${d.title.toLowerCase()}"><div class="principle-head" onclick="toggleCard('card-${c.id}')"><span class="principle-num">${c.id}</span><span class="principle-emoji">${c.emoji}</span><span class="principle-title">${d.title}</span><span class="principle-chev">&#9660;</span></div><div class="principle-body"><div class="principle-inner"><p class="principle-desc">${d.desc}</p><div class="verse-box"><div class="verse-arabic">${d.quran}</div><div class="verse-ref">${d.quranRef}</div></div><div class="action-box"><span class="action-icon">💡</span><span>${d.lesson}</span></div><button class="share-btn" onclick="event.stopPropagation();shareCard(${i})"><span class="share-icon">&#128279;</span> ${t.share}</button></div></div></div>`; }).join('');
  document.getElementById('cardsContainer').innerHTML = searchBar + cards;
}
function filterCards(query) { const q = query.toLowerCase().trim(); document.querySelectorAll('.principle-card').forEach(card => { const searchText = card.dataset.search || ''; const title = card.querySelector('.principle-title'); const titleText = title ? title.textContent.toLowerCase() : ''; card.style.display = (!q || searchText.includes(q) || titleText.includes(q)) ? '' : 'none'; }); }
async function shareCard(idx) { const c = CARDS[idx]; const d = c[lang]; const text = `${c.emoji} ${d.title}\n\n${d.desc}\n\n${d.quran}\n💡 ${d.lesson}\n\n— الاستعمار أحقاد وأطماع`; if (navigator.share) { try { await navigator.share({ title: d.title, text }); } catch(e) {} } else { try { await navigator.clipboard.writeText(text); showToast(lang === 'ar' ? 'تم النسخ!' : lang === 'fr' ? 'Copié !' : 'Copied!'); } catch(e) { showToast('Could not copy'); } } }

function renderResistance() {
  const t = T[lang];
  document.getElementById('resistanceContainer').innerHTML = RESISTANCE_DATA.map(r => { const d = r[lang]; return `<div class="anxiety-card scroll-reveal"><div class="anxiety-header"><span class="anxiety-emoji">${r.emoji}</span><span class="anxiety-title">${d.title}</span></div><div class="anxiety-problem"><span class="anxiety-label">${lang==='ar'?'😰 المشكلة':lang==='fr'?'😰 Le Problème':'😰 The Problem'}</span>${d.problem}</div><div class="anxiety-solution"><span class="anxiety-label">${lang==='ar'?'🛡️ الحل':lang==='fr'?'🛡️ La Solution':'🛡️ The Solution'}</span>${d.solution}</div><div class="verse-box"><div class="verse-arabic">${d.verse}</div><div class="verse-ref">${d.verseRef}</div></div></div>`; }).join('');
}

function renderHabits() {
  const today = new Date().toDateString(); let habitsState = JSON.parse(localStorage.getItem('istimar-habits') || '{}');
  if (habitsState.date !== today) { updateStreak(habitsState); habitsState = { date: today, done: [] }; localStorage.setItem('istimar-habits', JSON.stringify(habitsState)); }
  const streak = getStreak(); const streakHTML = streak > 0 ? `<div class="streak-badge">🔥 ${streak} ${T[lang].streakMsg}</div>` : '';
  document.getElementById('habitsContainer').innerHTML = HABITS.map((h, i) => { const d = h[lang]; const isDone = habitsState.done.includes(i); return `<div class="habit-item ${isDone ? 'done' : ''}" onclick="toggleHabit(${i})"><span class="habit-check">${isDone ? '&#10003;' : ''}</span><span class="habit-emoji">${h.emoji}</span><div><div class="habit-label">${d.label}</div><div class="habit-source">${d.source}</div></div></div>`; }).join('');
  const streakEl = document.getElementById('streakBadge'); if (streakEl) streakEl.innerHTML = streakHTML; updateHabitsProgress(habitsState);
}
function toggleHabit(i) { const today = new Date().toDateString(); let hs = JSON.parse(localStorage.getItem('istimar-habits') || '{}'); if (hs.date !== today) hs = { date: today, done: [] }; const idx = hs.done.indexOf(i); if (idx > -1) hs.done.splice(idx, 1); else hs.done.push(i); localStorage.setItem('istimar-habits', JSON.stringify(hs)); renderHabits(); playSound(idx > -1 ? 'click' : 'success'); if (hs.done.length === HABITS.length) { launchConfetti(); showToast(T[lang].allDone); } }
function resetHabits() { localStorage.setItem('istimar-habits', JSON.stringify({ date: new Date().toDateString(), done: [] })); renderHabits(); showToast(lang === 'ar' ? 'تم إعادة التعيين' : lang === 'fr' ? 'Réinitialisé' : 'Reset'); }
function updateHabitsProgress(hs) { const done = hs.done.length, total = HABITS.length, pct = total > 0 ? (done / total * 100) : 0; const fill = document.getElementById('habitsFill'); const txt = document.getElementById('habitsText'); if (fill) fill.style.width = pct + '%'; if (txt) txt.textContent = `${done}/${total}`; }
function updateStreak(prevState) { let streakData = JSON.parse(localStorage.getItem('istimar-streak') || '{"count":0,"lastDate":""}'); if (prevState && prevState.done && prevState.done.length === HABITS.length && prevState.date) { const yesterday = new Date(); yesterday.setDate(yesterday.getDate() - 1); if (prevState.date === yesterday.toDateString()) streakData.count++; else if (prevState.date !== new Date().toDateString()) streakData.count = prevState.done.length === HABITS.length ? 1 : 0; streakData.lastDate = prevState.date; } else if (prevState && prevState.date) { streakData.count = 0; streakData.lastDate = prevState.date; } localStorage.setItem('istimar-streak', JSON.stringify(streakData)); }
function getStreak() { return JSON.parse(localStorage.getItem('istimar-streak') || '{"count":0}').count; }

function launchConfetti() { const canvas = document.getElementById('confettiCanvas'); if (!canvas) return; canvas.style.display = 'block'; const ctx = canvas.getContext('2d'); canvas.width = window.innerWidth; canvas.height = window.innerHeight; const particles = []; const colors = ['#3E2723','#5D4037','#795548','#8D6E63','#A1887F','#BCAAA4','#4E342E']; for (let i = 0; i < 120; i++) particles.push({ x:Math.random()*canvas.width, y:Math.random()*canvas.height-canvas.height, w:Math.random()*10+5, h:Math.random()*6+3, color:colors[Math.floor(Math.random()*colors.length)], vx:(Math.random()-0.5)*4, vy:Math.random()*3+2, rot:Math.random()*360, rotSpeed:(Math.random()-0.5)*10 }); let frame = 0; function draw() { ctx.clearRect(0, 0, canvas.width, canvas.height); particles.forEach(p => { p.x += p.vx; p.y += p.vy; p.rot += p.rotSpeed; ctx.save(); ctx.translate(p.x, p.y); ctx.rotate(p.rot * Math.PI / 180); ctx.fillStyle = p.color; ctx.fillRect(-p.w/2, -p.h/2, p.w, p.h); ctx.restore(); }); frame++; if (frame < 120) requestAnimationFrame(draw); else { ctx.clearRect(0, 0, canvas.width, canvas.height); canvas.style.display = 'none'; } } draw(); }

function renderQuiz() {
  const t = T[lang];
  document.getElementById('quizContainer').innerHTML = QUIZ.map((q, i) => `<div class="quiz-question scroll-reveal" id="quiz-q-${i}"><div class="quiz-q-text">${i+1}. ${q[lang]}</div><div class="quiz-options"><button class="quiz-opt" onclick="selectQuizOpt(${i},2)">${t.yes}</button><button class="quiz-opt" onclick="selectQuizOpt(${i},1)">${t.sometimes}</button><button class="quiz-opt" onclick="selectQuizOpt(${i},0)">${t.no}</button></div></div>`).join('') + `<button class="quiz-submit" onclick="submitQuiz()">${t.submitQuiz}</button>`;
  document.getElementById('quizResult').classList.add('hidden'); window._quizAnswers = {};
}
function selectQuizOpt(qi, val) { window._quizAnswers[qi] = val; document.querySelectorAll(`#quiz-q-${qi} .quiz-opt`).forEach((o, oi) => o.classList.toggle('selected', [2,1,0][oi] === val)); playSound('click'); }
function submitQuiz() {
  const answers = window._quizAnswers || {}; if (Object.keys(answers).length < QUIZ.length) { showToast(lang === 'ar' ? 'أجب على جميع الأسئلة' : lang === 'fr' ? 'Répondez à toutes les questions' : 'Answer all questions'); return; }
  const invertedQs = [1, 3]; let score = 0; Object.entries(answers).forEach(([qi, v]) => { score += invertedQs.includes(parseInt(qi)) ? (2 - v) : v; });
  const max = QUIZ.length * 2, pct = Math.round(score / max * 100); let emoji, title, desc;
  if (pct >= 75) { emoji = '🌟'; title = lang==='ar'?'ممتاز!':lang==='fr'?'Excellent !':'Excellent!'; desc = lang==='ar'?'وعيك بقضايا الاستعمار عالٍ. استمر!':lang==='fr'?'Votre conscience du colonialisme est élevée !':'Your awareness of colonialism is high!'; }
  else if (pct >= 50) { emoji = '🛡️'; title = lang==='ar'?'جيد':lang==='fr'?'Bien':'Good'; desc = lang==='ar'?'أنت على الطريق الصحيح. طوّر وعيك أكثر.':lang==='fr'?'Vous êtes sur la bonne voie. Développez votre conscience.':'You\'re on the right track. Develop your awareness more.'; }
  else { emoji = '📢'; title = lang==='ar'?'حان وقت الوعي':lang==='fr'?'Il est temps de s\'éveiller':'Time to Wake Up'; desc = lang==='ar'?'أنت بحاجة لمزيد من الوعي. ابدأ بقراءة البطاقات.':lang==='fr'?'Vous avez besoin de plus de conscience. Commencez par les cartes.':'You need more awareness. Start by reading the cards.'; }
  const result = document.getElementById('quizResult'); result.classList.remove('hidden');
  result.innerHTML = `<div class="qr-emoji">${emoji}</div><div class="qr-score">${pct}%</div><div class="qr-title">${title}</div><div class="qr-desc">${desc}</div><button class="quiz-submit" onclick="renderQuiz()" style="margin-top:16px">${T[lang].quizAgain}</button>`;
  result.scrollIntoView({ behavior: 'smooth' }); playSound('success');
}

function renderAbout() {
  const about = {
    ar: { disclaimerTitle:'⚠️ تنبيه مهم', disclaimer:'لست عالماً ولا مفتياً. هذا جهد متواضع من مسلم يحب كتب الشيخ الغزالي. المحتوى مستمد من الكتاب ومصادر إسلامية موثوقة. ليست فتوى.', authorName:'الشيخ محمد الغزالي', authorDates:'١٩١٧ — ١٩٩٦', authorBio:'عالم ومفكر إسلامي مصري، لُقب بـ"أديب الدعوة". ألّف أكثر من ٩٤ كتاباً. درس في الأزهر، ودرّس في جامعة الأمير عبد القادر بقسنطينة (الجزائر).', bookTitle:'عن الكتاب', bookDesc:'"الاستعمار أحقاد وأطماع" يكشف الشيخ الغزالي فيه الوجه الحقيقي للاستعمار الغربي، مبيناً أطماعه الاقتصادية وأحقاده الدينية وأساليبه في تدمير هوية الشعوب المسلمة. يتناول الكتاب الحملات الصليبية، التبشير، الاستشراق، والاستعمار الجديد، مع تقديم رؤية إسلامية للمقاومة والتحرر.', sourcesTitle:'المصادر', sources:['كتاب "الاستعمار أحقاد وأطماع" — الشيخ محمد الغزالي','القرآن الكريم','صحيح البخاري ومسلم'], contact:'تواصل: abdelhak.bourdim@gmail.com' },
    en: { disclaimerTitle:'⚠️ Important Notice', disclaimer:'I am not a scholar or mufti. This is a humble effort by a Muslim who loves Sheikh al-Ghazali\'s books. Content is derived from the book and trusted Islamic sources. This is not a fatwa.', authorName:'Sheikh Mohammed al-Ghazali', authorDates:'1917 — 1996', authorBio:'Egyptian Islamic scholar and thinker, nicknamed "The Literary Preacher." Author of 94+ books. Studied at Al-Azhar, taught at the University of Emir Abdelkader in Constantine, Algeria.', bookTitle:'About the Book', bookDesc:'"Colonialism: Grudges and Greed" by Sheikh al-Ghazali exposes the true face of Western colonialism, revealing its economic greed and religious grudges and methods of destroying Muslim peoples\' identity. The book covers the Crusades, missionary work, Orientalism, and neo-colonialism, presenting an Islamic vision for resistance and liberation.', sourcesTitle:'Sources', sources:['"Colonialism: Grudges and Greed" — Sheikh Mohammed al-Ghazali','The Holy Quran','Sahih al-Bukhari and Muslim'], contact:'Contact: abdelhak.bourdim@gmail.com' },
    fr: { disclaimerTitle:'⚠️ Avis Important', disclaimer:'Je ne suis ni savant ni mufti. C\'est un effort humble d\'un musulman qui aime les livres du Sheikh al-Ghazali. Le contenu est tiré du livre et de sources islamiques fiables. Ce n\'est pas une fatwa.', authorName:'Sheikh Mohammed al-Ghazali', authorDates:'1917 — 1996', authorBio:'Savant et penseur islamique égyptien, surnommé « Le Littéraire de la Prédication ». Auteur de plus de 94 livres. Diplômé d\'Al-Azhar, professeur à l\'Université Émir Abdelkader de Constantine (Algérie).', bookTitle:'À Propos du Livre', bookDesc:'« Le Colonialisme : Rancunes et Avidité » du Sheikh al-Ghazali dévoile le vrai visage du colonialisme occidental, révélant son avidité économique et ses rancunes religieuses. Le livre couvre les Croisades, le prosélytisme, l\'orientalisme et le néo-colonialisme, présentant une vision islamique pour la résistance et la libération.', sourcesTitle:'Sources', sources:['« Le Colonialisme : Rancunes et Avidité » — Sheikh Mohammed al-Ghazali','Le Saint Coran','Sahih al-Bukhari et Muslim'], contact:'Contact : abdelhak.bourdim@gmail.com' }
  };
  const a = about[lang];
  document.getElementById('aboutContainer').innerHTML = `<div class="about-disclaimer"><div class="about-disclaimer-title">${a.disclaimerTitle}</div><p>${a.disclaimer}</p></div><div class="about-author"><span class="about-author-icon">📚</span><div class="about-author-info"><div class="about-author-name">${a.authorName}</div><div class="about-author-dates">${a.authorDates}</div><div class="about-author-bio">${a.authorBio}</div></div></div><div class="about-section"><div class="about-section-title">${a.bookTitle}</div><p class="about-text">${a.bookDesc}</p></div><div class="about-section"><div class="about-section-title">${a.sourcesTitle}</div>${a.sources.map(s => `<p class="about-text">&#8226; ${s}</p>`).join('')}</div><div class="about-section"><p class="about-text">${a.contact}</p></div>`;
}

function renderHelp() {
  const help = { ar:[{title:'⚠️ تنبيه',body:'لست عالماً. هذا جهد متواضع لنشر حكمة الشيخ الغزالي.'},{title:'📚 المصادر',body:'كتاب "الاستعمار أحقاد وأطماع" للشيخ محمد الغزالي، القرآن الكريم.'},{title:'✨ المميزات',body:'ثلاث لغات، ٣ أنماط، ٢٠ بطاقة، ٥ حلول للمقاومة، تتبع العادات، اختبار.'},{title:'⌨️ اختصارات',body:'الأسهم للتنقل. Escape لإغلاق اللوحات.'}], en:[{title:'⚠️ Disclaimer',body:'I am not a scholar. This is a humble effort to share Sheikh al-Ghazali\'s wisdom.'},{title:'📚 Sources',body:'"Colonialism: Grudges and Greed" by Sheikh al-Ghazali, the Holy Quran.'},{title:'✨ Features',body:'Three languages, 3 themes, 20 cards, 5 resistance solutions, habit tracker, quiz.'},{title:'⌨️ Shortcuts',body:'Arrow keys to navigate. Escape to close panels.'}], fr:[{title:'⚠️ Avertissement',body:'Je ne suis pas un savant. C\'est un effort humble pour partager la sagesse du Sheikh.'},{title:'📚 Sources',body:'« Le Colonialisme » par Sheikh al-Ghazali, le Saint Coran.'},{title:'✨ Fonctionnalités',body:'Trois langues, 3 thèmes, 20 cartes, 5 solutions de résistance, habitudes, quiz.'},{title:'⌨️ Raccourcis',body:'Flèches pour naviguer. Échap pour fermer.'}] };
  document.getElementById('helpBody').innerHTML = help[lang].map(h => `<div class="help-item"><div class="help-item-title">${h.title}</div><div>${h.body}</div></div>`).join('');
}

function renderDuas() { document.getElementById('duaPanelContent').innerHTML = DUAS.map(d => { const dd = d[lang]; return `<div class="dua-item"><div class="dua-item-label">${dd.label}</div><div class="dua-item-ar">${dd.text}</div><div class="dua-item-tr">${dd.tr}</div></div>`; }).join(''); }

function initScrollReveal() { if (!('IntersectionObserver' in window)) return; const observer = new IntersectionObserver((entries) => { entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add('revealed'); observer.unobserve(entry.target); } }); }, { threshold: 0.08, rootMargin: '0px 0px -40px 0px' }); document.querySelectorAll('.scroll-reveal:not(.revealed)').forEach(el => observer.observe(el)); document.querySelectorAll('.tab').forEach(tab => { tab.addEventListener('click', () => setTimeout(() => { document.querySelectorAll('.scroll-reveal:not(.revealed)').forEach(el => observer.observe(el)); }, 100)); }); }

function initKeyboardNav() { document.addEventListener('keydown', (e) => { if (e.key === 'Escape') { const helpPanel = document.getElementById('helpPanel'); if (!helpPanel.classList.contains('hidden')) { toggleHelp(); return; } const duaPanel = document.getElementById('duaPanel'); if (!duaPanel.classList.contains('hidden')) { toggleDuaPanel(); return; } document.querySelectorAll('.principle-card.open').forEach(c => c.classList.remove('open')); } if (e.key === 'ArrowRight' || e.key === 'ArrowLeft') { const cardsPanel = document.getElementById('panel-cards'); if (!cardsPanel || !cardsPanel.classList.contains('active')) return; if (document.activeElement && document.activeElement.id === 'cardsSearch') return; e.preventDefault(); const cards = Array.from(document.querySelectorAll('.principle-card')).filter(c => c.style.display !== 'none'); if (cards.length === 0) return; if (currentCardIdx >= 0 && currentCardIdx < cards.length) cards[currentCardIdx].classList.remove('open'); const dir = (document.documentElement.dir === 'rtl') ? (e.key === 'ArrowRight' ? -1 : 1) : (e.key === 'ArrowRight' ? 1 : -1); currentCardIdx = Math.max(0, Math.min(cards.length - 1, currentCardIdx + dir)); cards[currentCardIdx].classList.add('open'); cards[currentCardIdx].scrollIntoView({ behavior: 'smooth', block: 'center' }); playSound('click'); } }); }

function toggleCard(id) { const card = document.getElementById(id); if (card) { card.classList.toggle('open'); playSound('click'); } }
function toggleHelp() { document.getElementById('helpPanel').classList.toggle('hidden'); playSound('click'); }
function toggleDuaPanel() { document.getElementById('duaPanel').classList.toggle('hidden'); playSound('click'); }
function showToast(msg) { const t = document.getElementById('toast'); const m = document.getElementById('toastMsg'); if (t && m) { m.textContent = msg; t.style.display = 'block'; setTimeout(() => t.style.display = 'none', 2500); } }
function initScrollTop() { const btn = document.getElementById('scrollTop'); window.addEventListener('scroll', () => { if (btn) btn.classList.toggle('visible', window.scrollY > 300); }); }

const AudioCtx = window.AudioContext || window.webkitAudioContext; let audioCtx;
function playSound(type) { try { if (!audioCtx) audioCtx = new AudioCtx(); const osc = audioCtx.createOscillator(); const gain = audioCtx.createGain(); osc.connect(gain); gain.connect(audioCtx.destination); gain.gain.value = 0.06; if (type === 'click') { osc.frequency.value = 800; osc.type = 'sine'; gain.gain.value = 0.04; } else if (type === 'success') { osc.frequency.value = 523; osc.type = 'sine'; } else if (type === 'theme') { osc.frequency.value = 440; osc.type = 'triangle'; gain.gain.value = 0.05; } osc.start(); osc.stop(audioCtx.currentTime + 0.1); } catch(e) {} }

function initSwipeGestures() { let touchStartX = 0, touchStartY = 0; const tabOrder = ['home','cards','resistance','habits','quiz','about']; document.addEventListener('touchstart', (e) => { touchStartX = e.changedTouches[0].screenX; touchStartY = e.changedTouches[0].screenY; }, { passive: true }); document.addEventListener('touchend', (e) => { const dx = e.changedTouches[0].screenX - touchStartX; const dy = e.changedTouches[0].screenY - touchStartY; if (Math.abs(dx) < 60 || Math.abs(dy) > Math.abs(dx) * 0.7) return; const currentTab = document.querySelector('.tab.active'); if (!currentTab) return; const currentIdx = tabOrder.indexOf(currentTab.dataset.tab); const isRTL = document.documentElement.dir === 'rtl'; let nextIdx; if (dx > 0) nextIdx = isRTL ? currentIdx + 1 : currentIdx - 1; else nextIdx = isRTL ? currentIdx - 1 : currentIdx + 1; nextIdx = Math.max(0, Math.min(tabOrder.length - 1, nextIdx)); if (nextIdx !== currentIdx) { const nextTab = document.querySelector(`[data-tab="${tabOrder[nextIdx]}"]`); if (nextTab) nextTab.click(); } }, { passive: true }); }

function initParticles() { const canvas = document.createElement('canvas'); canvas.className = 'particles-canvas'; document.body.appendChild(canvas); const ctx = canvas.getContext('2d'); let particles = []; const colors = ['rgba(62,39,35,0.12)','rgba(93,64,55,0.1)','rgba(121,85,72,0.08)','rgba(78,52,46,0.1)']; function resize() { canvas.width = window.innerWidth; canvas.height = window.innerHeight; } resize(); window.addEventListener('resize', resize); for (let i = 0; i < 20; i++) particles.push({ x:Math.random()*canvas.width, y:Math.random()*canvas.height, r:Math.random()*4+2, vy:-(Math.random()*0.3+0.1), vx:(Math.random()-0.5)*0.2, color:colors[Math.floor(Math.random()*colors.length)] }); function draw() { ctx.clearRect(0, 0, canvas.width, canvas.height); particles.forEach(p => { ctx.beginPath(); ctx.arc(p.x, p.y, p.r, 0, Math.PI*2); ctx.fillStyle = p.color; ctx.fill(); p.y += p.vy; p.x += p.vx; if (p.y < -10) { p.y = canvas.height + 10; p.x = Math.random() * canvas.width; } if (p.x < -10) p.x = canvas.width + 10; if (p.x > canvas.width + 10) p.x = -10; }); requestAnimationFrame(draw); } draw(); }
